declare module '@department-of-veterans-affairs/component-library/dist/react-bindings' {
  export const __esModule: boolean
  export const VaAccordion: any
  export const VaAccordionItem: any
  export const VaAdditionalInfo: any
  export const VaAlert: any
  export const VaAlertExpandable: any
  export const VaBackToTop: any
  export const VaBanner: any
  export const VaBreadcrumbs: any
  export const VaButton: any
  export const VaButtonPair: any
  export const VaCard: any
  export const VaCheckbox: any
  export const VaCheckboxGroup: any
  export const VaCrisisLineModal: any
  export const VaDate: any
  export const VaFeaturedContent: any
  export const VaFileInput: any
  export const VaHeaderMinimal: any
  export const VaIcon: any
  export const VaLink: any
  export const VaLoadingIndicator: any
  export const VaMaintenanceBanner: any
  export const VaMemorableDate: any
  export const VaMinimalFooter: any
  export const VaModal: any
  export const VaNeedHelp: any
  export const VaNotification: any
  export const VaNumberInput: any
  export const VaOfficialGovBanner: any
  export const VaOmbInfo: any
  export const VaOnThisPage: any
  export const VaPagination: any
  export const VaPrivacyAgreement: any
  export const VaProcessList: any
  export const VaProcessListItem: any
  export const VaProgressBar: any
  export const VaPromoBanner: any
  export const VaRadio: any
  export const VaRadioOption: any
  export const VaSearchInput: any
  export const VaSegmentedProgressBar: any
  export const VaSelect: any
  export const VaStatementOfTruth: any
  export const VaTable: any
  export const VaTableRow: any
  export const VaTelephone: any
  export const VaTextInput: any
  export const VaTextarea: any
}
